version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - chatapp

networks:
  chatapp:
    driver: bridge